spring:
  kafka:
    bootstrap-servers: "172.21.170.170:9092"
    consumer:
      group-id: "spring-kafka"
      #      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
