server.port: 8900

spring:
  profiles:
    active: database,kafka,redis,store,elasticsearch
  application:
    name: scaffold-server
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    property-naming-strategy: SNAKE_CASE
    time-zone: Asia/Shanghai


springdoc:
  api-docs:
    # 是否开启文档功能
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    #自定义 swagger 前端请求路径，输入 http：127.0.0.1:8900/swagger-ui 会自动重定向到 swagger 页面
    path: /swagger-ui
  #包扫描路径 wang.diff.scaffold.controller,wang.diff.scaffold.dto.request
  #  packages-to-scan: wang.diff.scaffold.controller
  group-configs:
    - group: admin #分组名
      packages-to-scan:
        - wang.diff.scaffold.controller.admin #按路径匹配
    - group: user #分组名
      packages-to-scan:
        - wang.diff.scaffold.controller.api
    - group: common
      packages-to-scan:
        - wang.diff.scaffold.controller.common #按包路径匹配
    - group: crond
      packages-to-scan:
        - wang.diff.scaffold.controller.crond #按包路径匹配

page-helper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true


logging:
  level:
    wang.diff.scaffold.dao: DEBUG # 看 sql
    wang.diff.scaffold.controller: DEBUG
  pattern:
    level: debug
#  file:
#    name: user-server.log
#    path: .

#    root: debug
#debug: true