spring:
  elasticsearch:
    uris: 192.168.1.227:9200
    username: elastic
    password: bl8ydfJJgq


logging:
  level:
    org.springframework.data.elasticsearch.core: DEBUG
    org.springframework.data.elasticsearch.client: DEBUG