spring:
  kafka:
    bootstrap-servers: "192.168.226.136:9092"
    consumer:
      group-id: "spring-kafka"
      #      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
