server.port: 8900

spring:
  application:
    name: scaffold-server
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    property-naming-strategy: SNAKE_CASE
    time-zone: Asia/Shanghai
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.226.136:3307/user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000
  liquibase:
    enabled: true
    change-log: classpath:/db/liquibase/changelog.xml


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  api-docs:
    # 是否开启文档功能
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    #自定义 swagger 前端请求路径，输入 http：127.0.0.1:8080/swagger-ui 会自动重定向到 swagger 页面
    path: /swagger-ui
  #包扫描路径 wang.diff.scaffold.controller,wang.diff.scaffold.dto.request
  #  packages-to-scan: wang.diff.scaffold.controller
  group-configs:
    - group: admin #分组名
      packages-to-scan:
        - wang.diff.scaffold.controller.admin #按路径匹配
    - group: user #分组名
      packages-to-scan:
        - wang.diff.scaffold.controller.api
    - group: common
      packages-to-scan:
        - wang.diff.scaffold.controller.common #按包路径匹配

page-helper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true