spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.226.136:3307/scaffold-springboot3?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000


  dynamic: # 多数据源
    primary: scaffold # 设置默认的数据源或者数据源组,默认值即为 master
    strict: false # 严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
    datasource:
      scaffold:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.226.136:3307/scaffold-springboot3?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      patient:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.226.136:3307/scaffold-springboot3?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000



  liquibase:
    enabled: true
    change-log: classpath:/db/liquibase/changelog.xml


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl